<?php

namespace Kysela;

class Tools extends \Nette\Object
{

	public static function getHash($text = 'I LOVE NETTE FRAMEWORK', $length = 128)
	{
		$chars = 'abcdefghijklmnopqrstuvwqyz0123456789abcdefghijklmnopqrstuvwqyz01234567893456789abcdef';
		$string = '';
				
		for ($i = 0; $i < 50; $i++)
		{
			$string .= $chars{mt_rand(0, strlen($chars) - 1)};
		}
    
		return substr(hash('sha512', sha1(microtime() . $string . $text . time())),0,$length);
	}
	
	public static function passwordHash($password, $salt)
	{
		return hash('sha512', hash_hmac('sha256', sha1($password), sha1($salt), true));
	}


	public static function getCountry($code = NULL) {
		$firstNations = array(
			'us' => 'Spojené státy americké',
			'cz' => 'Česká republika',
			);
		$nations = array(
			'af' => 'Islámská republika Afghánistán',
			'al' => 'Albánská republika',
			'aq' => 'Antarktida',
			'dz' => 'Alžírská demokratická a lidová republika',
			'as' => 'Americká Samoa',
			'ad' => 'Andorrské knížectví',
			'ao' => 'Angolská republika',
			'ag' => 'Antigua a Barbuda',
			'az' => 'Ázerbájdžánská republika',
			'ar' => 'Argentinská republika',
			'au' => 'Austrálie',
			'at' => 'Rakouská republika',
			'bs' => 'Bahamské společenství',
			'bh' => 'Království Bahrajn',
			'bd' => 'Bangladéšská lidová republika',
			'am' => 'Arménská republika',
			'bb' => 'Barbados',
			'be' => 'Belgické království',
			'bm' => 'Bermudy',
			'bt' => 'Bhútánské království',
			'bo' => 'Mnohonárodní stát Bolívie',
			'ba' => 'Bosna a Hercegovina',
			'bw' => 'Republika Botswana',
			'bv' => 'Bouvetův ostrov',
			'br' => 'Brazilská federativní republika',
			'bz' => 'Belize',
			'io' => 'Britské indickooceánské území',
			'sb' => 'Šalomounovy ostrovy',
			'vg' => 'Britské Panenské ostrovy',
			'xk' => 'Republika Kosovo',
			'bn' => 'Brunej Darussalam',
			'bg' => 'Bulharská republika',
			'mm' => 'Republika Myanmarský svaz',
			'bi' => 'Republika Burundi',
			'by' => 'Běloruská republika',
			'kh' => 'Kambodžské království',
			'cm' => 'Kamerunská republika',
			'ca' => 'Kanada',
			'cv' => 'Kapverdská republika',
			'ky' => 'Kajmanské ostrovy',
			'cf' => 'Středoafrická republika',
			'lk' => 'Srílanská demokratická socialistická republika',
			'td' => 'Čadská republika',
			'cl' => 'Chilská republika',
			'cn' => 'Čínská lidová republika',
			'tw' => 'Tchaj-wan (čínská provincie)',
			'cx' => 'Vánoční ostrov',
			'cc' => 'Kokosové (Keelingovy) ostrovy',
			'co' => 'Kolumbijská republika',
			'km' => 'Komorský svaz',
			'yt' => 'Mayotte',
			'cg' => 'Konžská republika',
			'cd' => 'Demokratická republika Kongo',
			'ck' => 'Cookovy ostrovy',
			'cr' => 'Kostarická republika',
			'hr' => 'Chorvatská republika',
			'cu' => 'Kubánská republika',
			'cy' => 'Kyperská republika',
			'bj' => 'Beninská republika',
			'dk' => 'Dánské království',
			'dm' => 'Dominické společenství',
			'do' => 'Dominikánská republika',
			'ec' => 'Ekvádorská republika',
			'sv' => 'Salvadorská republika',
			'gq' => 'Republika Rovníková Guinea',
			'et' => 'Etiopská federativní demokratická republika',
			'er' => 'Eritrea',
			'ee' => 'Estonská republika',
			'fo' => 'Faerské ostrovy',
			'fk' => 'Falklandské ostrovy (Malvíny)',
			'gs' => 'Jižní Georgie a Jižní Sandwichovy ostrovy',
			'fj' => 'Fidžijská republika',
			'fi' => 'Finská republika',
			'ax' => 'Alandské ostrovy',
			'fr' => 'Francouzská republika',
			'gf' => 'Francouzská Guyana',
			'pf' => 'Francouzská Polynésie',
			'tf' => 'Francouzská jižní území',
			'dj' => 'Džibutská republika',
			'ga' => 'Gabonská republika',
			'ge' => 'Gruzie',
			'gm' => 'Gambijská republika',
			'ps' => 'Okupované palestinské území',
			'de' => 'Spolková republika Německo',
			'gh' => 'Ghanská republika',
			'gi' => 'Gibraltar',
			'ki' => 'Republika Kiribati',
			'gr' => 'Řecká republika',
			'gl' => 'Grónsko',
			'gd' => 'Grenada',
			'gp' => 'Guadeloupe',
			'gu' => 'Guam',
			'gt' => 'Guatemalská republika',
			'gn' => 'Guinejská republika',
			'gy' => 'Guyanská republika',
			'ht' => 'Republika Haiti',
			'hm' => 'Heardův ostrov a McDonaldovy ostrovy',
			'va' => 'Svatý stolec (Vatikánský městský stát)',
			'hn' => 'Honduraská republika',
			'hk' => 'Zvláštní administrativní oblast Číny Hongkong',
			'hu' => 'Maďarská republika',
			'is' => 'Islandská republika',
			'in' => 'Indická republika',
			'id' => 'Indonéská republika',
			'ir' => 'Íránská islámská republika',
			'iq' => 'Irácká republika',
			'ie' => 'Irsko',
			'il' => 'Stát Izrael',
			'it' => 'Italská republika',
			'ci' => 'Republika Pobřeží Slonoviny',
			'jm' => 'Jamajka',
			'jp' => 'Japonsko',
			'kz' => 'Republika Kazachstán',
			'jo' => 'Jordánské hášimovské království',
			'ke' => 'Keňská republika',
			'kp' => 'Korejská lidově demokratická republika',
			'kr' => 'Korejská republika',
			'kw' => 'Stát Kuvajt',
			'kg' => 'Kyrgyzská republika',
			'la' => 'Laoská lidově demokratická republika',
			'lb' => 'Libanonská republika',
			'ls' => 'Království Lesotho',
			'lv' => 'Lotyšská republika',
			'lr' => 'Liberijská republika',
			'ly' => 'Velká libyjská arabská lidová socialistická džamáhírije',
			'li' => 'Lichtenštejnské knížectví',
			'lt' => 'Litevská republika',
			'lu' => 'Lucemburské velkovévodství',
			'mo' => 'Zvláštní administrativní oblast Číny Macao',
			'mg' => 'Madagaskarská republika',
			'mw' => 'Republika Malawi',
			'my' => 'Malajsie',
			'mv' => 'Maledivská republika',
			'ml' => 'Republika Mali',
			'mt' => 'Maltská republika',
			'mq' => 'Martinik',
			'mr' => 'Mauritánská islámská republika',
			'mu' => 'Mauricijská republika',
			'mx' => 'Spojené státy mexické',
			'mc' => 'Monacké knížectví',
			'mn' => 'Mongolsko',
			'md' => 'Moldavská republika',
			'me' => 'Černá Hora',
			'ms' => 'Montserrat',
			'ma' => 'Marocké království',
			'mz' => 'Mosambická republika',
			'om' => 'Sultanát Omán',
			'na' => 'Namibijská republika',
			'nr' => 'Republika Nauru',
			'np' => 'Nepálská federativní demokratická republika',
			'nl' => 'Nizozemské království',
			'cw' => 'Curaçao',
			'aw' => 'Aruba',
			'sx' => 'Svatý Martin (nizozemská část)',
			'bq' => 'Bonaire, Svatý Eustach a Saba',
			'nc' => 'Nová Kaledonie',
			'vu' => 'Republika Vanuatu',
			'nz' => 'Nový Zéland',
			'ni' => 'Nikaragujská republika',
			'ne' => 'Nigerská republika',
			'ng' => 'Nigerijská federativní republika',
			'nu' => 'Niue',
			'nf' => 'Ostrov Norfolk',
			'no' => 'Norské království',
			'mp' => 'Společenství Ostrovy Severní Mariany',
			'um' => 'Menší odlehlé ostrovy USA',
			'fm' => 'Federativní státy Mikronésie',
			'mh' => 'Republika Marshallovy ostrovy',
			'pw' => 'Republika Palau',
			'pk' => 'Pákistánská islámská republika',
			'pa' => 'Panamská republika',
			'pg' => 'Papua Nová Guinea',
			'py' => 'Paraguayská republika',
			'pe' => 'Peruánská republika',
			'ph' => 'Filipínská republika',
			'pn' => 'Pitcairn',
			'pl' => 'Polská republika',
			'pt' => 'Portugalská republika',
			'gw' => 'Republika Guinea-Bissau',
			'tl' => 'Demokratická republika Východní Timor',
			'pr' => 'Portoriko',
			'qa' => 'Stát Katar',
			're' => 'Réunion',
			'ro' => 'Rumunsko',
			'ru' => 'Ruská federace',
			'rw' => 'Republika Rwanda',
			'bl' => 'Saint Barthélemy',
			'sh' => 'Svatá Helena, Ascension a Tristan da Cunha',
			'kn' => 'Svatý Kryštof a Nevis',
			'ai' => 'Anguilla',
			'lc' => 'Svatá Lucie',
			'mf' => 'Svatý Martin (francouzská část)',
			'pm' => 'Saint Pierre a Miquelon',
			'vc' => 'Svatý Vincenc a Grenadiny',
			'sm' => 'Republika San Marino',
			'st' => 'Demokratická republika Svatý Tomáš a Princův ostrov',
			'sa' => 'Království Saúdská Arábie',
			'sn' => 'Senegalská republika',
			'rs' => 'Republika Srbsko',
			'sc' => 'Seychelská republika',
			'sl' => 'Republika Sierra Leone',
			'sg' => 'Singapurská republika',
			'sk' => 'Slovenská republika',
			'vn' => 'Vietnamská socialistická republika',
			'si' => 'Slovinská republika',
			'so' => 'Somálská republika',
			'za' => 'Jihoafrická republika',
			'zw' => 'Republika Zimbabwe',
			'es' => 'Španělské království',
			'ss' => 'Jihosúdánská republika',
			'sd' => 'Súdánská republika',
			'eh' => 'Západní Sahara',
			'sr' => 'Surinamská republika',
			'sj' => 'Svalbard a Jan Mayen',
			'sz' => 'Svazijské království',
			'se' => 'Švédské království',
			'ch' => 'Švýcarská konfederace',
			'sy' => 'Syrská arabská republika',
			'tj' => 'Republika Tádžikistán',
			'th' => 'Thajské království',
			'tg' => 'Republika Togo',
			'tk' => 'Tokelau',
			'to' => 'Království Tonga',
			'tt' => 'Republika Trinidad a Tobago',
			'ae' => 'Spojené arabské emiráty',
			'tn' => 'Tuniská republika',
			'tr' => 'Turecká republika',
			'tm' => 'Turkmenistán',
			'tc' => 'Ostrovy Turks a Caicos',
			'tv' => 'Tuvalu',
			'ug' => 'Ugandská republika',
			'ua' => 'Ukrajina',
			'mk' => 'Bývalá jugoslávská republika Makedonie',
			'eg' => 'Egyptská arabská republika',
			'gb' => 'Spojené království Velké Británie a Severního Irska',
			'gg' => 'Guernsey',
			'je' => 'Jersey',
			'im' => 'Ostrov Man',
			'tz' => 'Tanzanská sjednocená republika',
			'vi' => 'Americké Panenské ostrovy',
			'bf' => 'Burkina Faso',
			'uy' => 'Uruguayská východní republika',
			'uz' => 'Republika Uzbekistán',
			've' => 'Bolívarovská republika Venezuela',
			'wf' => 'Ostrovy Wallis a Futuna',
			'ws' => 'Nezávislý stát Samoa',
			'ye' => 'Jemenská republika',
			'zm' => 'Zambijská republika',			
		);
		
		asort($nations);
		
		//dump(array($firstNations, $nations));
		
		$n = \Nette\Utils\Arrays::mergeTree($firstNations, $nations);
		
		if ($code !== NULL)
		{
			if (in_array($code, $n))
			{
				return $n[$code];
			} else {
				// Národnost nenalezena
				return FALSE;
			}
		}
		
		return $n;
	}

}